# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{scrub}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matthew Mongeau"]
  s.date = %q{2010-02-02}
  s.description = %q{Scrub files with ease and elbow grease}
  s.email = %q{matt@toastyapps.com}
  s.files = [
    ".gitignore",
     "Rakefile",
     "Readme.textile",
     "VERSION",
     "lib/scrub.rb",
     "lib/scrubber.rb",
     "scrub.gemspec"
  ]
  s.homepage = %q{http://github.com/toastyapps/scrub}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Scrub files with ease and elbow grease}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

